apiVersion: v1
kind: ConfigMap
metadata:
  name: ray-hub-service-cm
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDsTCCApmgAwIBAgIUPxYAcZTm7G4UjZoKJJfawoESVtMwDQYJKoZIhvcNAQEL
    BQAwaDELMAkGA1UEBhMCSU4xEDAOBgNVBAgMB0d1amFyYXQxEjAQBgNVBAcMCUFo
    bWVkYWJhZDEQMA4GA1UECgwHcmF5bGlmZTEPMA0GA1UECwwGUm9vdENBMRAwDgYD
    VQQDDAdyb290LmNhMB4XDTI1MDIxMzA2MzY1OFoXDTM1MDIxMTA2MzY1OFowaDEL
    MAkGA1UEBhMCSU4xEDAOBgNVBAgMB0d1amFyYXQxEjAQBgNVBAcMCUFobWVkYWJh
    ZDEQMA4GA1UECgwHcmF5bGlmZTEPMA0GA1UECwwGUm9vdENBMRAwDgYDVQQDDAdy
    b290LmNhMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA2juOs9yC6fOr
    Coucyd2G6Akrh02Sg19buVVJVHuaCajH53++fALC3E2LZzqx01C8yQVlB3JgxTzG
    RKXo9M9UJ3YNXIp17xzfFiGUrPQsoaPQA+rM6fgurmZdqZ8Y0w4BTlDEzU8hCm1j
    QuoX4aI+7bdMeWOBNsZFzI72jA5muttWNYjL6+3iOUshn8ZF/8kRjqiXB7NwJRpZ
    r2ZRqsyAyRkTPdr3I838AuFKU3cekhaXNy92FZvpq75dUe+0gYHmS/1yo6wnLNqy
    yweOgB71rGZdPRVPB+AOku7/uOf+X4bJutj8oHfPH+Ncw+A78qt3kIgF9+Z8SyId
    WP5oNIo1/wIDAQABo1MwUTAdBgNVHQ4EFgQUhOf4lht1SB4NCs81EWM327m1ApQw
    HwYDVR0jBBgwFoAUhOf4lht1SB4NCs81EWM327m1ApQwDwYDVR0TAQH/BAUwAwEB
    /zANBgkqhkiG9w0BAQsFAAOCAQEAC5O3EZMG6K4kKfa3c4OaIeisj8BDUpcD+mKf
    cJRPaIGlsuhqlc5vKdVPTVHyc40g4L3F8G0LFmEFMpDcdso1eEqEp16s4yI2/Ndj
    o1L6SzcDgUiQ6OiHEEONjHdbhoWAU5Oj5gcSpDQvx1OvrfqA2TU79fOYsiXjGMwW
    rPXjSGHsw7nUc6LxY1REX7YDWAmcBQUVEqSPAtuo4qqk6n4SrvVU7JPnA4F6qtHa
    x5MU9QGLcqniYZzFTIqkkRjmqqFWkYT66jz4HGj6vV5QxtZF5wSXWsVqkICEOMze
    5kmGpL38jCS5m+J5YZkowbOwF1zMutmDt01JMo5xv92xnvcSHQ==
    -----END CERTIFICATE-----


  subca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDxDCCAqygAwIBAgIUAmdMmKdcpZKrqmE3d+BGkwVfXYswDQYJKoZIhvcNAQEL
    BQAwaDELMAkGA1UEBhMCSU4xEDAOBgNVBAgMB0d1amFyYXQxEjAQBgNVBAcMCUFo
    bWVkYWJhZDEQMA4GA1UECgwHcmF5bGlmZTEPMA0GA1UECwwGUm9vdENBMRAwDgYD
    VQQDDAdyb290LmNhMB4XDTI1MDIxMzA2MzcwMFoXDTMwMDIxMjA2MzcwMFowezEL
    MAkGA1UEBhMCSU4xEDAOBgNVBAgMB0d1amFyYXQxEjAQBgNVBAcMCUFobWVkYWJh
    ZDEQMA4GA1UECgwHcmF5bGlmZTEXMBUGA1UECwwOSW50ZXJtZWRpYXRlQ0ExGzAZ
    BgNVBAMMEnN1YmNhLnJheS5pbnRlcm5hbDCCASIwDQYJKoZIhvcNAQEBBQADggEP
    ADCCAQoCggEBAKPFb641gB4nplI1Oq23Jm4gyxqrHaHX+ZM3JECxda1WS/Aygf9G
    GI+JIx1CmgivYFdSlWZR3NCqRTYOHRD6Pr/I8j3uZJan2MnIU/eysrPf6FqOTlrE
    XC8WZosGD9T8pSAOGOghGs7u7THqwXCTRExtu6/VzWFLK0fEhxeFX4f/llzHkkOm
    x7cvuc1ITnlPb211ZP8ktnBy2m1mod3fvH8oeVm65MhCjfJ/HGLWAr4si+KeDBve
    K58Yu5PMAd7kY9FajkEOAehQHULXJlr1LjVHpYXtixOYdCzCwH0YbmaDSw6PT9aD
    z/EdHK8n6rk7OXIYtpU9B/DnsXON4xLzjTkCAwEAAaNTMFEwDwYDVR0TBAgwBgEB
    /wIBADAdBgNVHQ4EFgQUBCJqa+HOgvQyyf4TlxE6kOOz3xowHwYDVR0jBBgwFoAU
    hOf4lht1SB4NCs81EWM327m1ApQwDQYJKoZIhvcNAQELBQADggEBACWWF9mnMwvi
    96pqMsujwy8f4qZSs2mxvXdMFARpI5c2brVsG0d67FVC9OGSU+AOmRHUKYshyP+I
    NzQM9FL+cLmQUlaAT+lLYsrB9nu/+eJTkGqMLrhKkgjcgI8R5MJCfbr5WjBDjQLs
    eI5qnwynKi3BPi9GfHVgKpaR/a2QGyDJDimX88a1o7ttDcC8pT+1yq3ZvVdTzfKo
    1tcJ9EkrAIoO10ODSSORMq6jfgER5qZvuQWNqdXFKkrS8stx47zqm4qwU6p+ahK9
    gzHjKdLiYQBrwcx1jKWUuG4ZE/0jRsuJHfSoMkbxcol8X/uc3O0UkrnWRcVqpKle
    Ke0ZJvYnOI4=
    -----END CERTIFICATE-----

  chain-ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDxDCCAqygAwIBAgIUAmdMmKdcpZKrqmE3d+BGkwVfXYswDQYJKoZIhvcNAQEL
    BQAwaDELMAkGA1UEBhMCSU4xEDAOBgNVBAgMB0d1amFyYXQxEjAQBgNVBAcMCUFo
    bWVkYWJhZDEQMA4GA1UECgwHcmF5bGlmZTEPMA0GA1UECwwGUm9vdENBMRAwDgYD
    VQQDDAdyb290LmNhMB4XDTI1MDIxMzA2MzcwMFoXDTMwMDIxMjA2MzcwMFowezEL
    MAkGA1UEBhMCSU4xEDAOBgNVBAgMB0d1amFyYXQxEjAQBgNVBAcMCUFobWVkYWJh
    ZDEQMA4GA1UECgwHcmF5bGlmZTEXMBUGA1UECwwOSW50ZXJtZWRpYXRlQ0ExGzAZ
    BgNVBAMMEnN1YmNhLnJheS5pbnRlcm5hbDCCASIwDQYJKoZIhvcNAQEBBQADggEP
    ADCCAQoCggEBAKPFb641gB4nplI1Oq23Jm4gyxqrHaHX+ZM3JECxda1WS/Aygf9G
    GI+JIx1CmgivYFdSlWZR3NCqRTYOHRD6Pr/I8j3uZJan2MnIU/eysrPf6FqOTlrE
    XC8WZosGD9T8pSAOGOghGs7u7THqwXCTRExtu6/VzWFLK0fEhxeFX4f/llzHkkOm
    x7cvuc1ITnlPb211ZP8ktnBy2m1mod3fvH8oeVm65MhCjfJ/HGLWAr4si+KeDBve
    K58Yu5PMAd7kY9FajkEOAehQHULXJlr1LjVHpYXtixOYdCzCwH0YbmaDSw6PT9aD
    z/EdHK8n6rk7OXIYtpU9B/DnsXON4xLzjTkCAwEAAaNTMFEwDwYDVR0TBAgwBgEB
    /wIBADAdBgNVHQ4EFgQUBCJqa+HOgvQyyf4TlxE6kOOz3xowHwYDVR0jBBgwFoAU
    hOf4lht1SB4NCs81EWM327m1ApQwDQYJKoZIhvcNAQELBQADggEBACWWF9mnMwvi
    96pqMsujwy8f4qZSs2mxvXdMFARpI5c2brVsG0d67FVC9OGSU+AOmRHUKYshyP+I
    NzQM9FL+cLmQUlaAT+lLYsrB9nu/+eJTkGqMLrhKkgjcgI8R5MJCfbr5WjBDjQLs
    eI5qnwynKi3BPi9GfHVgKpaR/a2QGyDJDimX88a1o7ttDcC8pT+1yq3ZvVdTzfKo
    1tcJ9EkrAIoO10ODSSORMq6jfgER5qZvuQWNqdXFKkrS8stx47zqm4qwU6p+ahK9
    gzHjKdLiYQBrwcx1jKWUuG4ZE/0jRsuJHfSoMkbxcol8X/uc3O0UkrnWRcVqpKle
    Ke0ZJvYnOI4=
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIIDsTCCApmgAwIBAgIUPxYAcZTm7G4UjZoKJJfawoESVtMwDQYJKoZIhvcNAQEL
    BQAwaDELMAkGA1UEBhMCSU4xEDAOBgNVBAgMB0d1amFyYXQxEjAQBgNVBAcMCUFo
    bWVkYWJhZDEQMA4GA1UECgwHcmF5bGlmZTEPMA0GA1UECwwGUm9vdENBMRAwDgYD
    VQQDDAdyb290LmNhMB4XDTI1MDIxMzA2MzY1OFoXDTM1MDIxMTA2MzY1OFowaDEL
    MAkGA1UEBhMCSU4xEDAOBgNVBAgMB0d1amFyYXQxEjAQBgNVBAcMCUFobWVkYWJh
    ZDEQMA4GA1UECgwHcmF5bGlmZTEPMA0GA1UECwwGUm9vdENBMRAwDgYDVQQDDAdy
    b290LmNhMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA2juOs9yC6fOr
    Coucyd2G6Akrh02Sg19buVVJVHuaCajH53++fALC3E2LZzqx01C8yQVlB3JgxTzG
    RKXo9M9UJ3YNXIp17xzfFiGUrPQsoaPQA+rM6fgurmZdqZ8Y0w4BTlDEzU8hCm1j
    QuoX4aI+7bdMeWOBNsZFzI72jA5muttWNYjL6+3iOUshn8ZF/8kRjqiXB7NwJRpZ
    r2ZRqsyAyRkTPdr3I838AuFKU3cekhaXNy92FZvpq75dUe+0gYHmS/1yo6wnLNqy
    yweOgB71rGZdPRVPB+AOku7/uOf+X4bJutj8oHfPH+Ncw+A78qt3kIgF9+Z8SyId
    WP5oNIo1/wIDAQABo1MwUTAdBgNVHQ4EFgQUhOf4lht1SB4NCs81EWM327m1ApQw
    HwYDVR0jBBgwFoAUhOf4lht1SB4NCs81EWM327m1ApQwDwYDVR0TAQH/BAUwAwEB
    /zANBgkqhkiG9w0BAQsFAAOCAQEAC5O3EZMG6K4kKfa3c4OaIeisj8BDUpcD+mKf
    cJRPaIGlsuhqlc5vKdVPTVHyc40g4L3F8G0LFmEFMpDcdso1eEqEp16s4yI2/Ndj
    o1L6SzcDgUiQ6OiHEEONjHdbhoWAU5Oj5gcSpDQvx1OvrfqA2TU79fOYsiXjGMwW
    rPXjSGHsw7nUc6LxY1REX7YDWAmcBQUVEqSPAtuo4qqk6n4SrvVU7JPnA4F6qtHa
    x5MU9QGLcqniYZzFTIqkkRjmqqFWkYT66jz4HGj6vV5QxtZF5wSXWsVqkICEOMze
    5kmGpL38jCS5m+J5YZkowbOwF1zMutmDt01JMo5xv92xnvcSHQ==
    -----END CERTIFICATE-----

  subca.key: |
    -----BEGIN PRIVATE KEY-----
    MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCjxW+uNYAeJ6ZS
    NTqttyZuIMsaqx2h1/mTNyRAsXWtVkvwMoH/RhiPiSMdQpoIr2BXUpVmUdzQqkU2
    Dh0Q+j6/yPI97mSWp9jJyFP3srKz3+hajk5axFwvFmaLBg/U/KUgDhjoIRrO7u0x
    6sFwk0RMbbuv1c1hSytHxIcXhV+H/5Zcx5JDpse3L7nNSE55T29tdWT/JLZwctpt
    ZqHd37x/KHlZuuTIQo3yfxxi1gK+LIvingwb3iufGLuTzAHe5GPRWo5BDgHoUB1C
    1yZa9S41R6WF7YsTmHQswsB9GG5mg0sOj0/Wg8/xHRyvJ+q5OzlyGLaVPQfw57Fz
    jeMS8405AgMBAAECggEAFa+qCX1LpRKWh1nFlqXDSL9+bZ5dmuYMxiX93rQxEz4z
    aY/in3FChNVByVjdqUtB3GZS4rzx2s7FQfJt/mbIwuAi1bkY6Es7HYMxvUHUQJXk
    gINKFGJem5yhgQTROWCoI/3B5hEmKeNBFQRTT6sslttMCG1tGBZaWZNIWUC/xPQI
    pOyg1eGFUvO5rOZAFJ8t1JyrJjhqU5/ZFz4voUlluxMHnKkW4f3PEnMzMj2uQp5U
    uM3QjLREaDtGsE18/HvdU2Q/emIqnUJc/wVQ3zruCuf928R/R68FoquHtLgDumbZ
    K9VA1be/vR5xV/V3goW2PcNL5LB9SIE38w5zA5QABQKBgQDecyloyDGZAXxRczG/
    0Qtigj315rE+GVEsCV+DbCQaJRb5BjdRW1CH3T3NMp1VMR4pXHALiO/aWA0QZGK6
    F5JOdFWurBSn5swOnzlUozRrIEVXp9p3ktkMiWjBFl1zUKVQMMG6wOsMHHlSWSdO
    M9oGHLYwMvmgd9TXH/myd8wkpQKBgQC8eK4bIXXeoMjXoD8TJCdz2r+syAFaB2e/
    9Gj4kXzjpDL6KLR2PcNvf2CS8Sf1lhDBwf7LGVlDUTAWbTbBODXhb//ep/1AvgAm
    71xdMBe/JDMyyX7uPYSRJRsFWGq3KpaCTk6mgwN4vMMp6Il85Bg0axo325qJq3zJ
    BGYpc6WeBQKBgCFwtnzl+27A5mtoIcZwKoH4ik/5ChQHwkgYcJ9VFmhHwxhUcuRs
    EcMa4zuBrF0uMRaOqtlREJ2GNxCLxruq53ebzXWgsMo8y9g232t1zV99Tm9K8HCh
    Rre3wGOmdQ3sxa00Zysn7S246hQTCvGaod/hWRIN17Dj0r80M1k84RdxAoGBAJZn
    iCnGjhXYIe9RxoQz+fgOvZ/ZDJsYBce9+HdFQ3E2/Cd+jGU/7NLxx9P793OZCk5V
    zkuuMvnxtHpxNZ0EipsZkgvR69zaw6xOoFsNoiW7cdA51L2zAjQCdInTgXYi2nGq
    pEFllEOp/+VV2UJ9lINgZU/mRHFRFQgmJpE15RkxAoGBAINGrS6peI28lZ03F5ym
    aZt9luOaZ7t6muxUb5u7HULfEKCXTZprH2HMGlFUmRyLaCdyIGXHG1l5KgLRBF6Q
    h+4tUR5LIbY4YeJwG/OYA87qeKwjApJ57ckBHmcksaR6GCfsUteyg+WHJXxnu0KK
    86JBDGCXY4WBpnw+rdsMRK1q
    -----END PRIVATE KEY-----

