apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - monitoring.yaml
  - ingress-nginx.yaml
  - longhorn-system.yaml
  - elastic-system.yaml
  - cert-manager.yaml
  - metallb.yaml
  - postgres.yaml
  - kafka.yaml
  - analytics.yaml