apiVersion: v1
kind: Service
metadata:
  name: ripple-engine-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/management/prometheus"  
    prometheus.io/port: "metrics"
  labels:
    app.kubernetes.io/part-of: ripple-engine-service
spec:
  type: NodePort
  selector:
    app: ripple-engine-service
  ports:
    - protocol: TCP
      port: 38102
      targetPort: 38102
      nodePort: 32102
      name: "metrics"