apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: flink-kubernetes-operator
  namespace: default
spec:
  interval: 1m
  url: https://archive.apache.org/dist/flink/flink-kubernetes-operator-1.6.0