apiVersion: v1
kind: Service
metadata:
  name: ray-batch-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/management/prometheus"  
    prometheus.io/port: "metrics"
  labels:
    app.kubernetes.io/part-of: ray-batch-service
spec:
  type: NodePort
  selector:
    app: ray-backup-service
  ports:
    - protocol: TCP
      port: 38113
      targetPort: 38113
      nodePort: 32113
      name: "metrics"