apiVersion: v1
kind: ConfigMap
metadata:
  name: ray-hub-service-cm
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDsTCCApmgAwIBAgIUCjBpY2uDDDKuQ8mWMMGy+C+XFZUwDQYJKoZIhvcNAQEL
    BQAwaDELMAkGA1UEBhMCSU4xEDAOBgNVBAgMB0d1amFyYXQxEjAQBgNVBAcMCUFo
    bWVkYWJhZDEQMA4GA1UECgwHcmF5bGlmZTEPMA0GA1UECwwGUm9vdENBMRAwDgYD
    VQQDDAdyb290LmNhMB4XDTI1MDMyNDA5MzQ0NVoXDTM1MDMyMjA5MzQ0NVowaDEL
    MAkGA1UEBhMCSU4xEDAOBgNVBAgMB0d1amFyYXQxEjAQBgNVBAcMCUFobWVkYWJh
    ZDEQMA4GA1UECgwHcmF5bGlmZTEPMA0GA1UECwwGUm9vdENBMRAwDgYDVQQDDAdy
    b290LmNhMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAzAD1BqbHINMP
    xW+FtIdh0iJ+AMZ7itmYhQXC8txlPWRIvgY4kOGeBY84hoyT0gYF77Ohm9KwDssk
    b2uxpUhXoo4tcgyHD4I55ECWAwcxcxBrLsUkJvWNSJueVyXrJl17Lf01lFO2kxlB
    5Qqfny4cbvof6hbCPybepriIbMREz/VOeA+FJOOKyySM6ANXNjEJDtyELXftY6PO
    crgucvF4482v4jTJJzkYOXHaUkyefL3qL8RbnVuGbnEXKa+PRK5T4ojh0tvSl6Wv
    g+xMMZjDcGkFDQLkQOdo/U46ZgVxy72taqhZdF+WKOuePtHCpzg3aDUF+ezd6iVi
    bDjUIy+yoQIDAQABo1MwUTAdBgNVHQ4EFgQUWpjhNTwmYLtr3sqzanFYSf61L+8w
    HwYDVR0jBBgwFoAUWpjhNTwmYLtr3sqzanFYSf61L+8wDwYDVR0TAQH/BAUwAwEB
    /zANBgkqhkiG9w0BAQsFAAOCAQEARk5TGDJ0bto9Xn4cXzJOVStaV/MD8xbOTtM4
    dda/RynGtpbalZhPxgjrLkpGSGY17+CSF6brK/9eFRmd+KEl21kHAsyb7j3+aiET
    L8+AJK1VCstq5CqevIExH6GCfx0H/TbvYTxbYMrI+SluHyuG/wJxYqBxGeFbW/QB
    /byqFHdB58u3kA1EZJgdjEx698n2MPfMEMZrpfH7W9Ma6ix8hHrj9ApdefHRR4v8
    hxES7TL81R0AbeQvHS9TPTHQ+YNxQxXyMwLSlB8Yw9bM5iOMGKlKXd3kmfowYtKf
    8l2JaFZH59HUWNgiNYyYDfcco8EkJs8dqK1SBnOPuOpVxEBy5Q==
    -----END CERTIFICATE-----


  subca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDwDCCAqigAwIBAgIUIc0mlJzj3rJnFZqbRKKo8aEIJ6IwDQYJKoZIhvcNAQEL
    BQAwaDELMAkGA1UEBhMCSU4xEDAOBgNVBAgMB0d1amFyYXQxEjAQBgNVBAcMCUFo
    bWVkYWJhZDEQMA4GA1UECgwHcmF5bGlmZTEPMA0GA1UECwwGUm9vdENBMRAwDgYD
    VQQDDAdyb290LmNhMB4XDTI1MDMyNDA5NDI1NFoXDTMwMDMyMzA5NDI1NFowdzEL
    MAkGA1UEBhMCSU4xEDAOBgNVBAgMB0d1amFyYXQxEjAQBgNVBAcMCUFobWVkYWJh
    ZDEQMA4GA1UECgwHcmF5bGlmZTEXMBUGA1UECwwOSW50ZXJtZWRpYXRlQ0ExFzAV
    BgNVBAMMDnN1YmNhLnJheS5saWZlMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIB
    CgKCAQEApsl+YRroJeq98JXap5Ed+JdPqGDmrjhm6vaDK/tDV45BYEPaK15k9+Z8
    Jvh4S1VxzRvrl1JtdQdivubBV7Xd+PxX+nj5eRHa2rFUYrngrWGyBBKPxgMfsEz+
    2cmWJ2B0cJTtNo5BXcWpUHdsiUrEv17d9oZwvBF3DbqhY4+8oEKngmVGyRaC2KEI
    YCvbf/QA3Vb61y/iXv00IN72/dETXCsC5dmwf/kRAxsEpurbyINwGpx5g9OYxNwT
    M9bpNRSpJDxbxGHVTKTPLcztXwUfh926F6spTWUboFggdZXUrKwlMwA94fKn6xNB
    LC0Fqq9+fL8aKaG5lKnGeufCaHDuJQIDAQABo1MwUTAPBgNVHRMECDAGAQH/AgEA
    MB0GA1UdDgQWBBQJwRnz+iZpzuqFxGWxNKXzzlOjqzAfBgNVHSMEGDAWgBRamOE1
    PCZgu2veyrNqcVhJ/rUv7zANBgkqhkiG9w0BAQsFAAOCAQEAapijM1l/jZZ/jUei
    Jey/1KruJLpru4/iK0sY+O/ginScmQkCNshaFQ6Zyf5LMlhc9NTtKunZevcUrXQo
    jAHMUBy0M3sFIAiG4Ou2CogdefAeSTJw9aXxyQIbOchN+m+8SFFZ0Sxx8tMxE07F
    p4euQK2qYQySrSYulLLhqLd2m/GP2O0U/GQIlEhRsxeafXeUEwdO+BpEDg7IVg9M
    oLzVLd6XynOlddKQL4AuWMVu+UmjDuB6zAjQXoHb4E4FonhRgpL2IVpCEsEBhfcK
    IP4lm/4JbWPNwal9G7OM90npTk2RSKSNngeED7QA6mW7Th5ab1aRXA34YH9F6+bl
    MgxHeg==
    -----END CERTIFICATE-----

  chain-ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDwDCCAqigAwIBAgIUIc0mlJzj3rJnFZqbRKKo8aEIJ6IwDQYJKoZIhvcNAQEL
    BQAwaDELMAkGA1UEBhMCSU4xEDAOBgNVBAgMB0d1amFyYXQxEjAQBgNVBAcMCUFo
    bWVkYWJhZDEQMA4GA1UECgwHcmF5bGlmZTEPMA0GA1UECwwGUm9vdENBMRAwDgYD
    VQQDDAdyb290LmNhMB4XDTI1MDMyNDA5NDI1NFoXDTMwMDMyMzA5NDI1NFowdzEL
    MAkGA1UEBhMCSU4xEDAOBgNVBAgMB0d1amFyYXQxEjAQBgNVBAcMCUFobWVkYWJh
    ZDEQMA4GA1UECgwHcmF5bGlmZTEXMBUGA1UECwwOSW50ZXJtZWRpYXRlQ0ExFzAV
    BgNVBAMMDnN1YmNhLnJheS5saWZlMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIB
    CgKCAQEApsl+YRroJeq98JXap5Ed+JdPqGDmrjhm6vaDK/tDV45BYEPaK15k9+Z8
    Jvh4S1VxzRvrl1JtdQdivubBV7Xd+PxX+nj5eRHa2rFUYrngrWGyBBKPxgMfsEz+
    2cmWJ2B0cJTtNo5BXcWpUHdsiUrEv17d9oZwvBF3DbqhY4+8oEKngmVGyRaC2KEI
    YCvbf/QA3Vb61y/iXv00IN72/dETXCsC5dmwf/kRAxsEpurbyINwGpx5g9OYxNwT
    M9bpNRSpJDxbxGHVTKTPLcztXwUfh926F6spTWUboFggdZXUrKwlMwA94fKn6xNB
    LC0Fqq9+fL8aKaG5lKnGeufCaHDuJQIDAQABo1MwUTAPBgNVHRMECDAGAQH/AgEA
    MB0GA1UdDgQWBBQJwRnz+iZpzuqFxGWxNKXzzlOjqzAfBgNVHSMEGDAWgBRamOE1
    PCZgu2veyrNqcVhJ/rUv7zANBgkqhkiG9w0BAQsFAAOCAQEAapijM1l/jZZ/jUei
    Jey/1KruJLpru4/iK0sY+O/ginScmQkCNshaFQ6Zyf5LMlhc9NTtKunZevcUrXQo
    jAHMUBy0M3sFIAiG4Ou2CogdefAeSTJw9aXxyQIbOchN+m+8SFFZ0Sxx8tMxE07F
    p4euQK2qYQySrSYulLLhqLd2m/GP2O0U/GQIlEhRsxeafXeUEwdO+BpEDg7IVg9M
    oLzVLd6XynOlddKQL4AuWMVu+UmjDuB6zAjQXoHb4E4FonhRgpL2IVpCEsEBhfcK
    IP4lm/4JbWPNwal9G7OM90npTk2RSKSNngeED7QA6mW7Th5ab1aRXA34YH9F6+bl
    MgxHeg==
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIIDsTCCApmgAwIBAgIUCjBpY2uDDDKuQ8mWMMGy+C+XFZUwDQYJKoZIhvcNAQEL
    BQAwaDELMAkGA1UEBhMCSU4xEDAOBgNVBAgMB0d1amFyYXQxEjAQBgNVBAcMCUFo
    bWVkYWJhZDEQMA4GA1UECgwHcmF5bGlmZTEPMA0GA1UECwwGUm9vdENBMRAwDgYD
    VQQDDAdyb290LmNhMB4XDTI1MDMyNDA5MzQ0NVoXDTM1MDMyMjA5MzQ0NVowaDEL
    MAkGA1UEBhMCSU4xEDAOBgNVBAgMB0d1amFyYXQxEjAQBgNVBAcMCUFobWVkYWJh
    ZDEQMA4GA1UECgwHcmF5bGlmZTEPMA0GA1UECwwGUm9vdENBMRAwDgYDVQQDDAdy
    b290LmNhMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAzAD1BqbHINMP
    xW+FtIdh0iJ+AMZ7itmYhQXC8txlPWRIvgY4kOGeBY84hoyT0gYF77Ohm9KwDssk
    b2uxpUhXoo4tcgyHD4I55ECWAwcxcxBrLsUkJvWNSJueVyXrJl17Lf01lFO2kxlB
    5Qqfny4cbvof6hbCPybepriIbMREz/VOeA+FJOOKyySM6ANXNjEJDtyELXftY6PO
    crgucvF4482v4jTJJzkYOXHaUkyefL3qL8RbnVuGbnEXKa+PRK5T4ojh0tvSl6Wv
    g+xMMZjDcGkFDQLkQOdo/U46ZgVxy72taqhZdF+WKOuePtHCpzg3aDUF+ezd6iVi
    bDjUIy+yoQIDAQABo1MwUTAdBgNVHQ4EFgQUWpjhNTwmYLtr3sqzanFYSf61L+8w
    HwYDVR0jBBgwFoAUWpjhNTwmYLtr3sqzanFYSf61L+8wDwYDVR0TAQH/BAUwAwEB
    /zANBgkqhkiG9w0BAQsFAAOCAQEARk5TGDJ0bto9Xn4cXzJOVStaV/MD8xbOTtM4
    dda/RynGtpbalZhPxgjrLkpGSGY17+CSF6brK/9eFRmd+KEl21kHAsyb7j3+aiET
    L8+AJK1VCstq5CqevIExH6GCfx0H/TbvYTxbYMrI+SluHyuG/wJxYqBxGeFbW/QB
    /byqFHdB58u3kA1EZJgdjEx698n2MPfMEMZrpfH7W9Ma6ix8hHrj9ApdefHRR4v8
    hxES7TL81R0AbeQvHS9TPTHQ+YNxQxXyMwLSlB8Yw9bM5iOMGKlKXd3kmfowYtKf
    8l2JaFZH59HUWNgiNYyYDfcco8EkJs8dqK1SBnOPuOpVxEBy5Q==
    -----END CERTIFICATE-----

  subca.key: |
    -----BEGIN PRIVATE KEY-----
    MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCmyX5hGugl6r3w
    ldqnkR34l0+oYOauOGbq9oMr+0NXjkFgQ9orXmT35nwm+HhLVXHNG+uXUm11B2K+
    5sFXtd34/Ff6ePl5EdrasVRiueCtYbIEEo/GAx+wTP7ZyZYnYHRwlO02jkFdxalQ
    d2yJSsS/Xt32hnC8EXcNuqFjj7ygQqeCZUbJFoLYoQhgK9t/9ADdVvrXL+Je/TQg
    3vb90RNcKwLl2bB/+REDGwSm6tvIg3AanHmD05jE3BMz1uk1FKkkPFvEYdVMpM8t
    zO1fBR+H3boXqylNZRugWCB1ldSsrCUzAD3h8qfrE0EsLQWqr358vxopobmUqcZ6
    58JocO4lAgMBAAECggEADILWsinj9PzYniczkCMh3H+x3UIq6Qc4ldKuO2/ymNWw
    4EEpaLGWQS/0K10zSDK4NxKrgmilEXoKGs1cU/wZEvVk6RhG3cwsfqqo10C1Ep8e
    jNEn9p/N3PpNmgsrMmLOdpJ+qntoelmv2NDN3recg3Qg535QDxTVTtLrinh3Ww29
    5YCvvlK4ZMo0M/Kz2yqUhFMsTrlG1hcnjhEPGh8BrkCBHm6ElHR6Y1FDSEtA7PpS
    RijBUbsZorjjVJZn5At5Q/njNw5cw5V1Nc/l1U2p33q3uBW3OJsD+ScsMzkX6jIm
    0+NWbQs6VBIY8Yx2G+4lgVBMt8jmIGiSj+/2K8oEgQKBgQDZueiuX5Ybf6KaAvaX
    SH7yMcBJyqUiGWWJWoBKZlXuWy9ARndYNgeMmxjMUQSNWmzMZOLU2GF1qkNprJtR
    G3UgkqjDG4RzpOMygcu8YPpqsg6XQSU0gFL6woQEq1dz1XDhjPs5l/qldeB8cch1
    H5Gumf4ifibV+BBute57w7xupQKBgQDEGzpZSg4cmoUA74yuzk0wgYU0iFAn8e1q
    q0Jm+g9iKPHmIba/XKyMj+pfqDjtelodP0gJS3KEbAsLV4DcwgLtMPMcmuD+HCov
    8L2zRV2wqookCG9rF5FS2mSLGoNwRRvEVq49pndCToCmEPdnrxujEcqEXW/PhokJ
    WqwSFVXpgQKBgCbKNGY8qWWky7dcp8o0JEnKC1QaQmlc1PYvpYObz9tza2usIj8Z
    ASdPyo88L+9vGMshfjglhNeNygzdr543ohp3hpGcKXDhA4lQDpg1PugbaPYRqSs9
    YYtDdHnQfPgqIr5Me8W7CfDIm4IQU4JqaW4OCXTjvM+KLoNK7n4mVT/xAoGBAK88
    LV2QQR/qK6N0a1/g1TTc5+zTSd0H38ELm+Bs3sY2FEIyKhzBcSaBi0tDBOugA1pT
    K8myc3hFG3FdFbcuXnMY5ITRGO+4tzHzi2/gMiIloh8ksnsdqixBHsr2PDFcb714
    P2azk6nagDbkvk8WODn1MeQpojns3BNRxKS8D/MBAoGAXToWw807BpAAaksgIHGQ
    SrkkheNDm6ejc+2MJs9Ba3Xd/63LN4StwCSplzQQ1NVRobi3uBr0N06swC4FB5X+
    lrJFHeeT4lN1iEl7mfTbe8mGQNqASOQXCUVXMeBMbzPZxQIlY2nXgDfvkauYQI/z
    1tTziJfvm6jNb15ZWcwTDRc=
    -----END PRIVATE KEY-----
