apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: controller-volume
  finalizers:
    - kubernetes.io/pvc-protection
  labels: 
    recurring-job.longhorn.io/source: enabled
    recurring-job.longhorn.io/recurring-backups: enabled
    recurring-job-group.longhorn.io/backup: enabled
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi