apiVersion: v1
kind: Service
metadata:
  name: ray-lighthouse-service
spec:
  type: NodePort
  selector:
    app: ray-lighthouse-service
  ports:
    - protocol: TCP
      port: 38116
      targetPort: 38116
      nodePort: 32116