apiVersion: v1
kind: Service
metadata:
  name: ray-jsreports-service
spec:
  type: NodePort
  selector:
    app: ray-jsreports-service
  ports:
    - protocol: TCP
      port: 5488
      targetPort: 5488
      nodePort: 32488