apiVersion: v1
kind: Service
metadata:
  name: ripple-nginx
spec:
  type: NodePort
  selector:
    app: ripple-nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 32103