apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  namespace: postgres
type: Opaque
data:
  AWS_ACCESS_KEY_ID: QVNJQTZHQk1EVENTUldVTElXWVI=
  AWS_SECRET_ACCESS_KEY: MHZPNWxuQUFjM29XeEI2NnRCNHU0UHBISmxmMFl0YlBrSlFIdW9vbQ==
  AWS_REGION: YXAtc291dGgtMQ==