apiVersion: v1
kind: Service
metadata:
  name: ray-gateway-service-headless
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: ray-gateway-service
  ports:
  - name: hazelcast
    port: 5701