apiVersion: v1
kind: Service
metadata:
  name: ray-audit-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/management/prometheus"  
    prometheus.io/port: "metrics"
  labels:
    app.kubernetes.io/part-of: ray-audit-service
spec:
  type: NodePort
  selector:
    app: ray-audit-service
  ports:
    - protocol: TCP
      port: 38085
      targetPort: 38085
      nodePort: 32085
      name: "metrics"