apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: prometheus-msteams
  namespace: monitoring
spec:
  interval: 1m
  url: https://prometheus-msteams.github.io/prometheus-msteams/