apiVersion: v1
kind: Service
metadata:
  labels:
    app: crate
  name: crate-internal-service
spec:
  ports:
  - name: crate-web
    port: 4200
    protocol: TCP
    targetPort: 4200
  - name: crate-internal
    port: 4300
    protocol: TCP
    targetPort: 4300
  - name: postgres
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: crate
  sessionAffinity: None
  type: NodePort
