apiVersion: v1
kind: Service
metadata:
  labels:
    app: crate-temp
  name: crate-internal-service-temp
spec:
  ports:
  - name: crate-web-t
    port: 4200
    protocol: TCP
    targetPort: 4200
  - name: crate-int-t
    port: 4300
    protocol: TCP
    targetPort: 4300
  - name: postgres-t
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: crate-temp
  sessionAffinity: None
  type: NodePort
