apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - deployment.yaml
  - crate-internal-service.yaml
  # - crate-internal-service-temp.yaml
  # - deployment-temp.yaml