apiVersion: v1
data:
  password: S1hWQlZEMmFNSmM5SXJ5d1dLWTFFbXlpS2pXampoOUhXVGlBWVdsejZZMUJuZWM3SEtTS1FOM0lvM1BIa1V2Rw==
  username: c3RhbmRieQ==
kind: Secret
metadata:
  labels:
    application: spilo
    cluster-name: postgres-postgresql
    recurring-job.longhorn.io/recurring-postgres-backups: enabled
    recurring-job.longhorn.io/source: enabled
    team: postgres
  name: standby.postgres-postgresql.credentials.postgresql.acid.zalan.do
  namespace: postgres
type: Opaque