apiVersion: batch/v1
kind: CronJob
metadata:
  name: postgres-backup
  namespace: postgres
spec:
  schedule: "*/1 * * * *"  
  jobTemplate:
    spec:
      template:
        spec:
          imagePullSecrets:
          - name: regcred
          containers:
          - name: postgres-backup
            image: truecomtelesoftindia/postgres-cronjob:latest  # Replace with your Docker image name
            command: ["/bin/sh", "-c", "/app/backup.sh"]
            imagePullPolicy: Always 
            envFrom: 
            - secretRef:
                name: aws-credentials
            env:
            - name: STORAGE_TYPE
              value: xyz
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: AWS_SECRET_ACCESS_KEY
            - name: AWS_REGION
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: AWS_REGION
            - name: S3_BUCKET
              value: s3://sujal-test-dump
            - name: DB_USER
              value: backup_user
            - name: DB_NAME
              value: RayApp
            - name: DB_PASSWORD
              value: Wf9dTq3Lu8Zr
            - name: DB_HOST
              value: postgres-postgresql-0.postgres-postgresql-hl.postgres.svc.cluster.local
            - name: SCHEMAS
              value: "controller hub notification radius statistics batch dashboard ripple_engine ray3p"
            resources:
              limits:
                cpu: "500m"
                memory: "512Mi"
              requests:
                cpu: "250m"
                memory: "256Mi"
          restartPolicy: OnFailure