apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
    name: ray-gateway-service-internal
spec:
  image: truecomtelesoftindia/ray-gateway-service
  interval: 1m0s
  secretRef:
    name: regcred