apiVersion: v1
kind: Service
metadata:
  labels:
    app: haproxy
    version: 2.0.0
  name: external-haproxy-service
spec:
  # externalTrafficPolicy: Cluster
  ports:
  - name: haproxy-stats
    port: 8998
    protocol: TCP
    targetPort: 8998
  - name: haproxy-mqtt
    port: 8884
    protocol: TCP
    targetPort: 8884
  - name: haproxy-plain
    port: 8883
    protocol: TCP
    targetPort: 8883
  selector:
    app: haproxy
    version: 3.0.0
  sessionAffinity: None
  type: NodePort

