apiVersion: v1
data:
  advanced.config: '[{vmq_server, [{tcp_listen_options,[{sndbuf, 32768},{recbuf, 32768}]}]}].'
  vmq.acl: |-
    pattern node/+/%u
    pattern node/+/+/%u
    pattern node/+/+/+/%u

    pattern command/%u
    pattern command/+/%u
    pattern command/+/+/%u

    pattern stations/+/+/%u
    pattern stations/+/+/+/%u

    pattern radius/+/+/%u
    pattern mesh/+/%u

    pattern visitedsites/+/%u

    pattern internet/+/%u
    pattern frontend/+/+/%u

    #websockets/stations/stats/fastUpdates/profileId/aa:bb
    pattern websockets/+/+/+/+/%u

    user admin
    topic #

    user websocketuser
    topic read websockets/#
kind: ConfigMap
metadata:
  name: vernemq-config
