apiVersion: v1
kind: Service
metadata:
  name: ray-radius-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/management/prometheus"  
    prometheus.io/port: "metrics"
  labels:
    app.kubernetes.io/part-of: ray-radius-service
spec:
  type: NodePort
  selector:
    app: ray-radius-service
  ports:
    - protocol: TCP
      port: 38086
      targetPort: 38086
      nodePort: 32086
      name: "metrics"