apiVersion: v1
kind: Service
metadata:
  labels:
    statefulset.kubernetes.io/pod-name: ray-mqtt-prod-0
  name: vernemq-pod-0
spec:
  type: NodePort
  selector:
    statefulset.kubernetes.io/pod-name: ray-mqtt-prod-0
  ports:
    - protocol: TCP
      port: 1884
      targetPort: 1884
      nodePort: 30005