apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: elasticsearch
  namespace: elastic-system
spec:
  interval: 1m
  url: https://helm.elastic.co  # Helm Repository Url