apiVersion: v1
kind: Service
metadata:
  name: ray-job-service
spec:
  type: NodePort
  selector:
    app: ray-job-service
  ports:
    - protocol: TCP
      port: 38082
      targetPort: 38082
      nodePort: 32082