apiVersion: v1
kind: Service
metadata:
  name: {{ template "cp-zookeeper.fullname" . }}-internal
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "{{ .Release.Name }}.test-kafka.internal"
    external-dns.alpha.kubernetes.io/ttl: "60"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: '60'
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: 'true'
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
  labels:
    app: {{ template "cp-zookeeper.name" . }}
    chart: {{ template "cp-zookeeper.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: LoadBalancer
  ports:
    - port: {{ .Values.clientPort }}
      name: client
    {{- if .Values.prometheus.jmx.enabled }}
    - name: metrics
      port: {{ .Values.prometheus.jmx.port }}
    {{- end }}
  selector:
    app: {{ template "cp-zookeeper.name" . }}
    release: {{ .Release.Name }}
